pipeline:
  name: pl_auto_pipeline_chnQ8
  identifier: pl_auto_pipeline_chnQ8
  orgIdentifier: DoNotDeleteTriggerOrg
  projectIdentifier: CDCNGAuto_CustomTrigger_0Do1s
  tags: { }
  stages:
      - stage:
          name: S1
          identifier: S1
          description: ""
          type: Custom
          spec:
            execution:
              steps:
                - step:
                    type: ShellScript
                    name: Shell Script_1
                    identifier: ShellScript_1
                    spec:
                      shell: Bash
                      onDelegate: true
                      source:
                        type: Inline
                        spec:
                          script: echo 'hi'
                      environmentVariables: [ ]
                      outputVariables: [ ]
                    timeout: 1m
          tags: { }