pipeline:
  name: pl_auto_pipeline_5kCfZ
  identifier: pl_auto_pipeline_5kCfZ
  orgIdentifier: DoNotDeleteTriggerOrg
  projectIdentifier: CDCNGAuto_TriggerProjJtfKhNVGD3
  tags: { }
  stages:
      - stage:
          name: S2
          identifier: S2
          description: ""
          type: Custom
          spec:
            execution:
              steps:
                - step:
                    type: Http
                    name: Http_1
                    identifier: Http_1
                    timeout: 10s
                    spec:
                      url: https://qa.harness.io/gateway/pipeline/api/webhook/custom/v2?accountIdentifier=rXUXvbFqRr2XwcjBu3Oq-Q&orgIdentifier=DoNotDeleteTriggerOrg&projectIdentifier=CDCNGAuto_TriggerProjJtfKhNVGD3&pipelineIdentifier=pl_auto_pipeline_DFSfr&triggerIdentifier=CDCNGAuto_Custom_Webhook_Trigger_S9AK1yNhre
                      method: POST
                      headers: [ ]
                      inputVariables: [ ]
                      outputVariables: [ ]
                      requestBody: "{\"sample_key\": \"sample_value\"}"
          tags: { }
