pipeline:
  name: pl_auto_pipeline_58fML
  identifier: pl_auto_pipeline_58fML
  orgIdentifier: DoNotDeleteTriggerOrg
  projectIdentifier: CDCNGAuto_CustomTrigger_jUXEf
  tags: { }
  stages:
      - stage:
          name: S2
          identifier: S2
          description: ""
          type: Custom
          spec:
            execution:
              steps:
                - step:
                    type: Http
                    name: Http_1
                    identifier: Http_1
                    timeout: 10s
                    spec:
                      url: https://smp-istio.test.harness.io/gateway/pipeline/api/webhook/custom/PS8-5UfrRzeakL2D_0UYqg/v3?accountIdentifier=waHpyKESSaqOqFRfd9uyHQ&orgIdentifier=DoNotDeleteTriggerOrg&projectIdentifier=CDCNGAuto_CustomTrigger_jUXEf&pipelineIdentifier=pl_auto_pipeline_UueIo&triggerIdentifier=CDNGAuto_Trigger_aDwX8s6u2N
                      method: POST
                      headers: [ ]
                      inputVariables: [ ]
                      outputVariables: [ ]
                      requestBody: "{\"sample_key\": \"sample_value\"}"
          tags: { }
