pipeline:
  name: pl_auto_pipeline_XZYGx
  identifier: pl_auto_pipeline_XZYGx
  orgIdentifier: DoNotDeleteTriggerOrg
  projectIdentifier: CDCNGAuto_CustomTrigger_OEowe
  tags: { }
  stages:
      - stage:
          name: S2
          identifier: S2
          description: ""
          type: Custom
          spec:
            execution:
              steps:
                - step:
                    type: Http
                    name: Http_1
                    identifier: Http_1
                    timeout: 10s
                    spec:
                      url: https://qa.harness.io/gateway/pipeline/api/webhook/custom/v2?accountIdentifier=rXUXvbFqRr2XwcjBu3Oq-Q&orgIdentifier=DoNotDeleteTriggerOrg&projectIdentifier=CDCNGAuto_CustomTrigger_OEowe&pipelineIdentifier=pl_auto_pipeline_ocewb&triggerIdentifier=CDNGAuto_Trigger_9zkxqr5vJF
                      method: POST
                      headers: [ ]
                      inputVariables: [ ]
                      outputVariables: [ ]
                      requestBody: "{\"sample_key\": \"sample_value\"}"
          tags: { }
