pipeline:
  name: pl_auto_pipeline_1OsCJ
  identifier: pl_auto_pipeline_1OsCJ
  orgIdentifier: DoNotDeleteTriggerOrg
  projectIdentifier: CDCNGAuto_TriggerProjKO76n12gOm
  tags: { }
  stages:
      - stage:
          name: S2
          identifier: S2
          description: ""
          type: Custom
          spec:
            execution:
              steps:
                - step:
                    type: Http
                    name: Http_1
                    identifier: Http_1
                    timeout: 10s
                    spec:
                      url: https://qa.harness.io/gateway/pipeline/api/webhook/custom/4mBS-Rj4Qne10UcmGsJx8A/v3?accountIdentifier=rXUXvbFqRr2XwcjBu3Oq-Q&orgIdentifier=DoNotDeleteTriggerOrg&projectIdentifier=CDCNGAuto_TriggerProjKO76n12gOm&pipelineIdentifier=pl_auto_pipeline_3WOkz&triggerIdentifier=CDCNGAuto_Custom_Webhook_Trigger_SZQVsXX0Ko
                      method: POST
                      headers: [ ]
                      inputVariables: [ ]
                      outputVariables: [ ]
                      requestBody: "{\"sample_key\": \"sample_value\"}"
          tags: { }
