pipeline:
  name: pl_auto_pipeline_Vnwqb
  identifier: pl_auto_pipeline_Vnwqb
  projectIdentifier: CDCNGAuto_CustomTrigger_FHLdI
  orgIdentifier: DoNotDeleteTriggerOrg
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: stage1
        type: Pipeline
        spec:
          org: DoNotDeleteTriggerOrg
          pipeline: pl_auto_pipeline_RxhUz
          project: CDCNGAuto_CustomTrigger_FHLdI